/* ==========================================================
   delete-premium-v6.js — PREMIUM V6
   Robust delete UI / API client that tries many variants
   - Compatible with Google Apps Script (Sheet1) endpoints
   - Tries GET variants, POST JSON variants, POST FormData fallback
   - Admin sees all; user sees only self and can only delete self
   - Auto logout if user deletes their own account
   - Requires config.js (window.API_URL) and delete.html structure

   Usage: include after config.js
   <script src="config.js"></script>
   <script src="delete-premium-v6.js"></script>

   DOM expectations in delete.html:
   - #userTableBody, #refreshBtn, #deleteSelectedBtn, #deleteAllBtn, #roleBadge

   Author: generated by assistant — Premium V6
   ========================================================== */

(function () {
  'use strict';
  // quick guard
  if (typeof window === 'undefined') return;

  // --- small UI helpers (toast + spinner) ---
  function ensureHelpers() {
    if (!document.getElementById('mft-toast')) {
      const t = document.createElement('div');
      t.id = 'mft-toast';
      Object.assign(t.style, {
        position: 'fixed', right: '18px', bottom: '18px', padding: '10px 14px',
        color: '#fff', fontWeight: 700, borderRadius: '10px', zIndex: 99999,
        display: 'none', boxShadow: '0 8px 30px rgba(0,0,0,0.12)', fontFamily: 'system-ui,Arial'
      });
      document.body.appendChild(t);
    }
    if (!document.getElementById('mft-spinner')) {
      const s = document.createElement('div');
      s.id = 'mft-spinner';
      Object.assign(s.style, {
        position: 'fixed', left: '50%', top: '28%', transform: 'translateX(-50%)',
        zIndex: 99998, display: 'none', padding: '12px 16px', borderRadius: '10px',
        boxShadow: '0 8px 30px rgba(0,0,0,0.12)', background: 'rgba(255,255,255,0.96)', fontFamily: 'system-ui,Arial'
      });
      s.innerHTML = '<div style="display:flex;gap:10px;align-items:center"><svg width="18" height="18" viewBox="0 0 50 50"><circle cx="25" cy="25" r="8" stroke="#1565c0" stroke-width="4" stroke-linecap="round" fill="none"><animateTransform attributeName="transform" type="rotate" from="0 25 25" to="360 25 25" dur="0.9s" repeatCount="indefinite"/></circle></svg><div style="font-weight:700;color:#333">Memproses...</div></div>';
      document.body.appendChild(s);
    }
  }

  function toast(msg, ok = true, ms = 2200) {
    const t = document.getElementById('mft-toast');
    if (!t) return console.log('toast:', msg);
    t.style.background = ok ? '#2e7d32' : '#c62828';
    t.textContent = msg;
    t.style.display = 'block';
    setTimeout(() => (t.style.display = 'none'), ms);
  }
  function showSpinner(sh = true) {
    const s = document.getElementById('mft-spinner');
    if (!s) return; s.style.display = sh ? 'block' : 'none';
  }

  ensureHelpers();

  // --- session ---
  let session = null;
  try { session = JSON.parse(localStorage.getItem('familyUser') || 'null'); } catch (e) { session = null; }
  if (!session || !session.token) {
    alert('Sesi tidak ditemukan. Silakan login ulang.');
    return location.href = 'login.html';
  }
  const TOKEN = session.token;
  const MY_ID = String(session.id);
  const MY_ROLE = (session.role || 'user').toLowerCase();

  // --- DOM refs ---
  const tbody = document.getElementById('userTableBody');
  const refreshBtn = document.getElementById('refreshBtn');
  const deleteSelectedBtn = document.getElementById('deleteSelectedBtn');
  const deleteAllBtn = document.getElementById('deleteAllBtn');
  const roleBadge = document.getElementById('roleBadge');

  if (!tbody) {
    toast('Tabel user tidak ditemukan pada halaman.', false, 3500);
    console.error('delete-premium-v6: missing #userTableBody');
    return;
  }

  if (roleBadge) roleBadge.innerHTML = `Peran: <b>${MY_ROLE}</b> (ID: ${MY_ID})`;

  // --- utils ---
  function esc(s) { if (s === undefined || s === null) return ''; return String(s).replace(/&/g,'&amp;').replace(/</g,'&lt;').replace(/>/g,'&gt;'); }
  function setBusy(btns, busy) { (btns||[]).forEach(b => { if (!b) return; b.disabled = busy; if (busy) b.classList && b.classList.add('disabled'); else b.classList && b.classList.remove('disabled'); }); }

  const API = window.API_URL || null;
  if (!API) {
    toast('config.js (API_URL) tidak ditemukan', false, 4000);
    console.error('delete-premium-v6: missing window.API_URL');
    return;
  }

  // --- fetch wrapper that returns {ok,json,raw,status,ctype,redirected} ---
  async function fetchRaw(url, opts = {}) {
    try {
      const r = await fetch(url, opts);
      const status = r.status;
      const ctype = r.headers.get('content-type') || '';
      const redirected = r.redirected || false;
      const text = await r.text();
      // try parse json
      try {
        const j = JSON.parse(text);
        return { ok: true, json: j, raw: text, status, ctype, redirected };
      } catch (e) {
        return { ok: false, json: null, raw: text, status, ctype, redirected };
      }
    } catch (err) {
      return { ok: false, error: String(err) };
    }
  }

  // --- normalize array extraction ---
  function extractArray(payload) {
    if (!payload) return [];
    if (Array.isArray(payload)) return payload;
    if (payload.status && Array.isArray(payload.data)) return payload.data;
    if (Array.isArray(payload.data)) return payload.data;
    if (Array.isArray(payload.items)) return payload.items;
    if (Array.isArray(payload.members)) return payload.members;
    // sometimes payload is {status:'success', data:{...}} where data itself contains arrays
    if (payload.data && typeof payload.data === 'object') {
      const maybe = Object.values(payload.data).find(v => Array.isArray(v));
      if (Array.isArray(maybe)) return maybe;
    }
    return [];
  }

  // --- render ---
  function renderRows(list) {
    if (!Array.isArray(list) || list.length === 0) {
      tbody.innerHTML = '<tr><td colspan="4" style="text-align:center;padding:18px;color:#666">Tidak ada user.</td></tr>';
      return;
    }
    // visible: admin or self
    const visible = (MY_ROLE === 'admin') ? list : list.filter(u => String(u.id ?? u.ID ?? u.Id ?? u.recordId) === MY_ID);
    if (!visible.length) {
      tbody.innerHTML = '<tr><td colspan="4" style="text-align:center;padding:18px;color:#666">Tidak ada user.</td></tr>';
      return;
    }
    const rows = visible.map(u => {
      const id = u.id ?? u.ID ?? u.Id ?? u.recordId ?? '';
      const name = u.name ?? u.nama ?? u.Name ?? '-';
      const dom = u.domisili ?? u.domisili ?? u.email ?? '-';
      const allow = (MY_ROLE === 'admin' || String(id) === MY_ID);
      const chk = allow ? `<input type="checkbox" class="mft-chk" value="${esc(id)}">` : `<input type="checkbox" class="mft-chk" value="${esc(id)}" disabled title="Hanya admin atau pemilik akun yang dapat menghapus">`;
      return `<tr><td style="text-align:center">${chk}</td><td style="word-break:break-all;min-width:220px">${esc(id)}</td><td>${esc(name)}</td><td>${esc(dom)}</td></tr>`;
    }).join('');
    tbody.innerHTML = rows;
  }

  // --- load users (try list -> getdata -> plain) ---
  async function loadUsers() {
    showSpinner(true);
    setBusy([refreshBtn, deleteSelectedBtn, deleteAllBtn], true);
    tbody.innerHTML = '<tr><td colspan="4" style="text-align:center;padding:18px;color:#666">Memuat data...</td></tr>';

    try {
      // try mode=list
      let r = await fetchRaw(`${API}?mode=list&token=${encodeURIComponent(TOKEN)}&ts=${Date.now()}`);
      if (r.ok && r.json) { renderRows(extractArray(r.json)); return; }

      // try mode=getdata
      r = await fetchRaw(`${API}?mode=getdata&token=${encodeURIComponent(TOKEN)}&ts=${Date.now()}`);
      if (r.ok && r.json) { renderRows(extractArray(r.json)); return; }

      // try without token
      r = await fetchRaw(`${API}?mode=getdata&ts=${Date.now()}`);
      if (r.ok && r.json) { renderRows(extractArray(r.json)); return; }

      // try root
      r = await fetchRaw(`${API}?ts=${Date.now()}`);
      if (r.ok && r.json) { renderRows(extractArray(r.json)); return; }

      // fallback: show server raw
      console.warn('All list/getdata attempts failed', r);
      tbody.innerHTML = '<tr><td colspan="4" style="text-align:center;padding:18px;color:#c0392b">Gagal memuat data (server). Periksa console/network.</td></tr>';
      toast('Gagal memuat data', false, 2600);

    } finally {
      showSpinner(false);
      setBusy([refreshBtn, deleteSelectedBtn, deleteAllBtn], false);
    }
  }

  // --- deletion logic: try variants (GET -> POST JSON -> POST FormData) ---
  async function tryDeleteOne(idValue) {
    if (!idValue) return { ok: false, reason: 'missing_id' };

    // 1) GET variants
    const getCandidates = [
      `${API}?mode=deleteMember&id=${encodeURIComponent(idValue)}&token=${encodeURIComponent(TOKEN)}`,
      `${API}?mode=delete&id=${encodeURIComponent(idValue)}&token=${encodeURIComponent(TOKEN)}`,
      `${API}?action=delete&id=${encodeURIComponent(idValue)}&token=${encodeURIComponent(TOKEN)}`,
      `${API}?mode=hardDelete&id=${encodeURIComponent(idValue)}&token=${encodeURIComponent(TOKEN)}`,
      `${API}?id=${encodeURIComponent(idValue)}&mode=delete&token=${encodeURIComponent(TOKEN)}`
    ];

    for (const url of getCandidates) {
      try {
        const r = await fetchRaw(url, { method: 'GET' });
        if (r.ok && r.json) {
          const s = r.json.status || r.json.ok || r.json.result;
          if (r.json.status === 'success' || r.json.status === 'ok' || (typeof s !== 'undefined' && s)) {
            return { ok: true, variant: 'get', url, json: r.json };
          }
        }
        // if redirected to HTML (login) or invalid JSON -> skip
      } catch (e) {}
    }

    // 2) POST JSON variants
    const postCandidates = [
      { mode: 'delete', id: idValue, token: TOKEN },
      { mode: 'deleteMember', id: idValue, token: TOKEN },
      { mode: 'hardDelete', id: idValue, token: TOKEN },
      { action: 'delete', id: idValue, token: TOKEN }
    ];

    for (const payload of postCandidates) {
      try {
        const r = await fetchRaw(API, {
          method: 'POST',
          headers: { 'Content-Type': 'application/json' },
          body: JSON.stringify(payload)
        });
        if (r.ok && r.json) {
          if (r.json.status === 'success' || r.json.status === 'ok' || (!r.json.status && Object.keys(r.json).length)) {
            return { ok: true, variant: 'post-json', payload, json: r.json };
          }
        }
      } catch (e) {}
    }

    // 3) POST FormData fallback (some GAS expect multipart)
    try {
      const fd = new FormData();
      fd.append('mode', 'delete');
      fd.append('id', idValue);
      fd.append('token', TOKEN);
      const r = await fetchRaw(API, { method: 'POST', body: fd });
      if (r.ok && r.json) {
        if (r.json.status === 'success' || r.json.status === 'ok' || !r.json.status) {
          return { ok: true, variant: 'post-form', json: r.json };
        }
      }
    } catch (e) {
      // continue
    }

    return { ok: false, reason: 'all_failed' };
  }

  async function deleteSelectedHandler() {
    const checked = Array.from(document.querySelectorAll('.mft-chk:checked')).map(i => i.value);
    if (!checked.length) return alert('Tidak ada user dipilih.');

    // non-admin may only delete themselves
    if (MY_ROLE !== 'admin') {
      const others = checked.filter(x => String(x) !== MY_ID);
      if (others.length) return alert('Anda hanya dapat menghapus akun Anda sendiri.');
    }

    if (!confirm(`Hapus ${checked.length} akun terpilih?`)) return;

    showSpinner(true);
    setBusy([refreshBtn, deleteSelectedBtn, deleteAllBtn], true);

    try {
      for (const id of checked) {
        const r = await tryDeleteOne(id);
        if (!r.ok) {
          console.error('Failed deleting id', id, r);
          toast(`Gagal hapus ID: ${id}`, false, 3500);
          return;
        }
        // if current user deleted — logout & redirect
        if (String(id) === MY_ID) {
          localStorage.removeItem('familyUser');
          alert('Akun Anda telah dihapus. Anda akan diarahkan ke login.');
          return location.href = 'login.html';
        }
      }
      toast('Penghapusan selesai.', true, 1800);
      await loadUsers();
    } finally {
      showSpinner(false);
      setBusy([refreshBtn, deleteSelectedBtn, deleteAllBtn], false);
    }
  }

  async function deleteAllHandler() {
    if (MY_ROLE !== 'admin') return alert('Hanya admin yang dapat menghapus semua user.');
    if (!confirm('\u26A0\uFE0F Yakin hapus SEMUA user? (tidak bisa dikembalikan)')) return;

    showSpinner(true);
    setBusy([refreshBtn, deleteSelectedBtn, deleteAllBtn], true);

    try {
      // get full list
      let r = await fetchRaw(`${API}?mode=list&token=${encodeURIComponent(TOKEN)}&ts=${Date.now()}`);
      let arr = [];
      if (r.ok && r.json) arr = extractArray(r.json);
      else {
        r = await fetchRaw(`${API}?mode=getdata&token=${encodeURIComponent(TOKEN)}&ts=${Date.now()}`);
        if (r.ok && r.json) arr = extractArray(r.json);
      }
      if (!Array.isArray(arr) || !arr.length) { toast('Gagal mengambil daftar user.', false, 2500); return; }

      for (const u of arr) {
        const id = u.id ?? u.ID ?? u.Id ?? null;
        if (!id) continue;
        const res = await tryDeleteOne(id);
        if (!res.ok) { console.error('deleteAll failed:', id, res); toast(`Gagal hapus ID: ${id}`, false, 3500); return; }
      }

      toast('Semua user berhasil dihapus.', true, 2400);
      await loadUsers();

    } finally {
      showSpinner(false);
      setBusy([refreshBtn, deleteSelectedBtn, deleteAllBtn], false);
    }
  }

  // wire events
  if (refreshBtn) refreshBtn.addEventListener('click', loadUsers);
  if (deleteSelectedBtn) deleteSelectedBtn.addEventListener('click', deleteSelectedHandler);
  if (deleteAllBtn) deleteAllBtn.addEventListener('click', deleteAllHandler);
  if (MY_ROLE !== 'admin' && deleteAllBtn) deleteAllBtn.style.display = 'none';

  // initial
  setTimeout(() => loadUsers(), 80);

  // expose debug
  window.mft = window.mft || {};
  window.mft.delete_v6 = { loadUsers, tryDeleteOne };

})();
